build\fibonaci.exp : fibonaci.c
	hcd386 fibonaci.c -obj build\fibonaci.OBJ
	386link build\fibonaci.obj @LIBS.LN -exe build\fibonaci.exp


build\failcase.exp : failcase.c
	hcd386 failcase.c -obj build\failcase.OBJ
	386link build\failcase.obj @LIBS.LN -exe build\failcase.exp


build\primesiz.exp : primesiz.c
	hcd386 primesiz.c -obj build\primesiz.OBJ
	386link build\primesiz.obj @LIBS.LN -exe build\primesiz.exp


build\makefrag.exp : makefrag.c
	hcd386 makefrag.c -obj build\makefrag.OBJ
	386link build\makefrag.obj @LIBS.LN -exe build\makefrag.exp


build\fwrite.exp : fwrite.c
	hcd386 fwrite.c -obj build\fwrite.OBJ
	386link build\fwrite.obj @LIBS.LN -exe build\fwrite.exp
