; TOWNSIO.ASM by CaptainYS

IO_FDC_STATUS			EQU		0200h
IO_FDC_COMMAND			EQU		0200h

IO_FDC_TRACK			EQU		0202h
IO_FDC_SECTOR			EQU		0204h
IO_FDC_DATA				EQU		0206h

IO_FDC_DRIVE_STATUS		EQU		0208h
IO_FDC_DRIVE_CONTROL	EQU		0208h

IO_FDC_DRIVE_SELECT		EQU		020Ch

IO_FDC_CMD_SEEK			EQU		010h
IO_FDC_CMD_READ_DATA	EQU		080h
IO_FDC_CMD_WRITE_DATA	EQU		0A0h


BIOSERR_DETAIL_DISK_DRIVE_NOT_READY		EQU		0001h
BIOSERR_DETAIL_DISK_SEEK_ERROR			EQU		0000h	; ?
BIOSERR_DETAIL_DISK_CRC_ERROR			EQU		0008h
BIOSERR_DETAIL_DISK_RECORD_NOT_FOUND	EQU		0010h
BIOSERR_DETAIL_DISK_LOST_DATA			EQU		0040h


SECTOR_LENGTH_1232KB_DISK		EQU		1024
SECTOR_PER_TRACK_1232KB_DISK	EQU		8

PHASE_FLAG_COMMAND		EQU		01H
PHASE_FLAG_DATA_IN		EQU		02H
PHASE_FLAG_MESSAGE		EQU		04H
PHASE_FLAG_STATUS		EQU		08H

IO_1US_WAIT				EQU		06CH	; Available after FM Towns 20F

IO_SCSI_DATA			EQU		0C30H
IO_SCSI_STATUS			EQU		0C32H
IO_SCSI_COMMAND			EQU		0C32H

IO_DMA_INITIALIZE		EQU		0A0H
IO_DMA_CHANNEL			EQU		0A1H
IO_DMA_COUNT_LOW		EQU		0A2H
IO_DMA_COUNT_HIGH		EQU		0A3H
IO_DMA_ADDR_LOW			EQU		0A4H
IO_DMA_ADDR_MID_LOW		EQU		0A5H
IO_DMA_ADDR_MID_HIGH	EQU		0A6H
IO_DMA_ADDR_HIGH		EQU		0A7H
IO_DMA_DEVICE_CTRL_LOW	EQU		0A8H
IO_DMA_DEVICE_CTRL_HIGH	EQU		0A9H
IO_DMA_MODE_CONTROL		EQU		0AAH
IO_DMA_STATUS			EQU		0ABH
IO_DMA_REQUEST			EQU		0AEH
IO_DMA_MASK				EQU		0AFH

IO_KEYBOARD_COMMAND		EQU		0602h
IO_KEYBOARD_STATUS		EQU		0602h
IO_KEYBOARD_DATA		EQU		0600h

DMA_CHANNEL_FDC			EQU		0
DMA_CHANNEL_SCSI		EQU		1
DMA_CHANNEL_PRINTER		EQU		2
DMA_CHANNEL_CDC			EQU		3

SCSI_MODE_DATA_IN		EQU		44H		; Data In (I/O to Mem)
SCSI_MODE_DATA_OUT		EQU		48H		; Data Out (Mem to I/O)

SCSI_STATUS_GOOD                      	EQU		0
SCSI_STATUS_CHECK_CONDITION           	EQU		02H
SCSI_STATUS_CONDITION_MET             	EQU		04H
SCSI_STATUS_BUSY                      	EQU		08H
SCSI_STATUS_INTERMEDIATE              	EQU		10H
SCSI_STATUS_INTERMEDIATE_CONDITION_MET	EQU		14H
SCSI_STATUS_RESERVATION_CONFLICT      	EQU		18H
SCSI_STATUS_COMMAND_TERMINATED        	EQU		22H
SCSI_STATUS_QUEUE_FULL                	EQU		28H

TOWNS_JISKEY_C			EQU		2Ch
TOWNS_JISKEY_D			EQU		20h
TOWNS_JISKEY_F			EQU		21h
TOWNS_JISKEY_H			EQU		23h
TOWNS_JISKEY_I			EQU		18h
TOWNS_JISKEY_M			EQU		30h

