; TOWNSIO.ASM by CaptainYS

IO_KVRAM_OR_ANKFONT   	EQU		0FF99H

IO_FREERUN_TIMER		EQU		0026H

IO_FDC_STATUS			EQU		0200h
IO_FDC_COMMAND			EQU		0200h

IO_FDC_TRACK			EQU		0202h
IO_FDC_SECTOR			EQU		0204h
IO_FDC_DATA				EQU		0206h

IO_FDC_DRIVE_STATUS		EQU		0208h
IO_FDC_DRIVE_CONTROL	EQU		0208h

IO_FDC_DRIVE_SELECT		EQU		020Ch

IO_FDC_CMD_SEEK			EQU		010h
IO_FDC_CMD_READ_DATA	EQU		080h
IO_FDC_CMD_WRITE_DATA	EQU		0A0h


BIOSERR_DETAIL_DISK_DRIVE_NOT_READY		EQU		0001h
BIOSERR_DETAIL_DISK_SEEK_ERROR			EQU		0000h	; ?
BIOSERR_DETAIL_DISK_CRC_ERROR			EQU		0008h
BIOSERR_DETAIL_DISK_RECORD_NOT_FOUND	EQU		0010h
BIOSERR_DETAIL_DISK_LOST_DATA			EQU		0040h

BIOSERR_DETAIL_HD_HARD_ERROR			EQU		0020h


SECTOR_LENGTH_1232KB_DISK		EQU		1024
SECTOR_PER_TRACK_1232KB_DISK	EQU		8

IO_KEYBOARD_COMMAND		EQU		0602h
IO_KEYBOARD_STATUS		EQU		0602h
IO_KEYBOARD_DATA		EQU		0600h

DMA_CHANNEL_FDC			EQU		0
DMA_CHANNEL_SCSI		EQU		1
DMA_CHANNEL_PRINTER		EQU		2
DMA_CHANNEL_CDC			EQU		3

SCSI_MODE_DATA_IN		EQU		44H		; Data In (I/O to Mem)
SCSI_MODE_DATA_OUT		EQU		48H		; Data Out (Mem to I/O)

TOWNS_JISKEY_C			EQU		2Ch
TOWNS_JISKEY_D			EQU		20h
TOWNS_JISKEY_F			EQU		21h
TOWNS_JISKEY_H			EQU		23h
TOWNS_JISKEY_I			EQU		18h
TOWNS_JISKEY_M			EQU		30h



CMOS_SCSI_PRESENT		EQU		3AC4h